# Generated by Django 5.2.9 on 2025-12-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(),
        ),
    ]
