# Generated by Django 5.2.9 on 2025-12-05 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('student', '0002_alter_student_name_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='products.products')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='student.student')),
            ],
        ),
    ]
